server:
  port: ${PORT}
  compression:
    enabled: true
    mime-types: application/json,text/html,text/xml,text/plain
    min-response-size: 1024

spring:
  application:
    name: SPHERICAL-SERVICE
  main:
    allow-bean-definition-overriding: true
  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT}
      password: ${SPRING_REDIS_PASSWORD}
      timeout: 5000ms

ghost:
  shield:
    key: ${GHOST_SHIELD_KEY}
    jwt-secret: ${JWT_SECRET}
  gateway:
    secret: ${GHOST_GATEWAY_SECRET}

user:
  catalog:
    service:
      name: ${USER_CATALOG_SERVICE_NAME}
      url: ${USER_SERVICE_URL}

moderation:
  openai:
    api-key: ${OPENAI_API_KEY}

logging:
  level:
    root: INFO
    com.AirDrop.Spherical: DEBUG